# Generated by Django 4.1.10 on 2023-11-28 11:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_status', models.CharField(default='bisa dijual', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.BigIntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(default='', max_length=100, null=True)),
                ('harga', models.DecimalField(decimal_places=2, default=100000, max_digits=12, null=True)),
                ('kategori_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Produk.kategori')),
                ('status_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Produk.status')),
            ],
        ),
    ]
