# Generated by Django 4.1.10 on 2023-11-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0002_alter_kategori_id_kategori_alter_produk_id_produk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='kategori_id',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='status_id',
            new_name='status',
        ),
    ]
