# Generated by Django 4.1.10 on 2023-11-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0003_rename_kategori_id_produk_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produk.kategori'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produk.status'),
        ),
    ]
