# Generated by Django 4.1.10 on 2023-11-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0005_alter_produk_kategori_alter_produk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='id_kategori',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id_status',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
