# Generated by Django 4.1.10 on 2023-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0006_alter_kategori_id_kategori_alter_produk_id_produk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.BigIntegerField(default=100000, null=True),
        ),
    ]
