# Generated by Django 4.1.10 on 2023-12-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produk', '0008_alter_kategori_nama_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
